name: ${COMPOSE_PROJECT_NAME}-dev

services:
  # Web 前端服务 - 使用 nginx 部署静态文件
  web:
    image: nginx:alpine
    container_name: pro-web-dev
    ports:
      - "${WEB_PORT:-8080}:80"
    volumes:
      # 挂载构建后的静态文件（需要先构建）
      - ./apps/web/dist/web/browser:/usr/share/nginx/html:ro
      # 挂载 nginx 配置
      - ./nginx/web.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.2'

  # Admin 管理后台 - 使用 nginx 部署静态文件
  admin:
    image: nginx:alpine
    container_name: pro-admin-dev
    ports:
      - "${ADMIN_PORT:-8081}:80"
    volumes:
      # 挂载构建后的静态文件（需要先构建）
      - ./apps/admin/dist/admin/browser:/usr/share/nginx/html:ro
      # 挂载 nginx 配置
      - ./nginx/admin.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.2'
