# Grafana数据源配置
# Grafana Datasources Configuration for Weibo Crawler System

apiVersion: 1

# 数据源列表
datasources:
  # Prometheus数据源
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-service:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}

  # Loki日志数据源（如果使用Loki）
  - name: Loki
    type: loki
    access: proxy
    url: http://loki-service:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"

  # Elasticsearch数据源（如果使用ELK）
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch-service:9200
    database: "weibo-crawler-*"
    jsonData:
      interval: "Daily"
      timeField: "@timestamp"
      esVersion: "8.0.0"
      maxConcurrentShardRequests: 5
      logMessageField: "message"
      logLevelField: "level"
      timeInterval: "1m"
    editable: true

  # InfluxDB数据源（如果使用InfluxDB）
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb-service:8086
    database: "weibo_crawler"
    user: "admin"
    jsonData:
      version: "Flux"
      organization: "company"
      defaultBucket: "weibo_crawler"
      tlsSkipVerify: true
    secureJsonData:
      password: "influxdb_password"
    editable: true

  # Jaeger追踪数据源
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-service:16686
    editable: true

  # PostgreSQL数据源
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres-service:5432
    database: pro
    user: pro
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: "postgres_password"
    editable: true

  # Redis数据源（通过Redis Explorer插件）
  - name: Redis
    type: redis-explorer
    access: proxy
    url: redis-service:6379
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 30
    secureJsonData:
      password: "redis_password"
    editable: true