# Secrets for Weibo Crawler System
apiVersion: v1
kind: Secret
metadata:
  name: crawler-secrets
  namespace: weibo-crawler
  labels:
    app: weibo-crawler
    component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  postgres-password: <BASE64_ENCODED_POSTGRES_PASSWORD>
  mongodb-username: <BASE64_ENCODED_MONGO_USERNAME>
  mongodb-password: <BASE64_ENCODED_MONGO_PASSWORD>
  redis-password: <BASE64_ENCODED_REDIS_PASSWORD>
  rabbitmq-username: <BASE64_ENCODED_RABBITMQ_USERNAME>
  rabbitmq-password: <BASE64_ENCODED_RABBITMQ_PASSWORD>
  minio-access-key: <BASE64_ENCODED_MINIO_ACCESS_KEY>
  minio-secret-key: <BASE64_ENCODED_MINIO_SECRET_KEY>

  # JWT secrets
  jwt-secret: <BASE64_ENCODED_JWT_SECRET>

  # Weibo account cookies (encrypted)
  weibo-cookies: <BASE64_ENCODED_WEIBO_COOKIES>

  # SSL certificates (if using self-signed)
  ssl-cert: <BASE64_ENCODED_SSL_CERT>
  ssl-key: <BASE64_ENCODED_SSL_KEY>

---
# TLS certificate secret (for HTTPS)
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: weibo-crawler
  labels:
    app: weibo-crawler
    component: tls
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_ENCODED_TLS_CERT>
  tls.key: <BASE64_ENCODED_TLS_KEY>

---
# Docker registry secret (if using private registry)
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: weibo-crawler
  labels:
    app: weibo-crawler
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_DOCKER_CONFIG>